### PR TITLE
fix/plugin/flutter-freezed adjusted generated code to follow what `freezed` package expects

### PR DESCRIPTION
**Pull request by auaicn**
🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

## Description

1. [part statement] inserted quotes and `.freezed` keyword in generated part statement
2. [Enum] separated values with `,` (comma) / for JsonKey, wrapped key with quotes
3. [fromJson] inserted dollar($) sign to follow freezed spec (see screenshots)

Related #8330

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### before [1]
image

### after [1]
image

### before [2]
image

### after [2]
image

### before [3]
image

### after [3]
image

## How Has This Been Tested?

- [x] updated `plugin.spec.ts` as I expected and saw passing result via `yarn test` command
- [x] updated `config.spec.ts` as I expected and saw passing result via `yarn test` command

There'were 5 failures but it seems not related to my changes

**Test Environment**:

- OS: macOS Monterey 12.2 (Apple M1)
- `@graphql-codegen/...`: base version was 2.11.1
- NodeJS: 13.14.0

## Checklist:

- [ ] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by auaicn** [comment]
@Parables 😀

**Comment by Parables** [comment]
@auaicn I am really grateful for your help. 

Great work.

**Comment by Parables** [comment]
@auaicn if I can ask for one more favour, please do take a look into the [/packages/plugins/dart/flutter-freezed/src/freezed-declaration-blocks/factory-block](https://github.com/Parables/graphql-code-generator/blob/6fbc54393b383e2ec7cd0a392cd9be6286697a95/packages/plugins/dart/flutter-freezed/src/freezed-declaration-blocks/factory-block.ts#L137) and figure out why there is a named constructor append to this factory block when using mergedInputs from the config.

Also, please update the tests for me. When I discovered these bugs, I had to make the test fail so that I could fix the bug and make them green again. Sadly enough, I haven't been able to get back to it ever since.

One more favour, please 🥺

**Comment by Parables** [comment]
@auaicn please send your PR to the [fluter-freezed-v3.0.0](https://github.com/Parables/graphql-code-generator/tree/fluter-freezed-v3.0.0) branch instead of the `master` so that you fetch the latest changes from my end.

And also about this:
> why there is a named constructor append to this factory block when using [mergedInputs](https://github.com/Parables/graphql-code-generator/blob/6fbc54393b383e2ec7cd0a392cd9be6286697a95/packages/plugins/dart/flutter-freezed/src/config.ts#L245) from the config.

Please see [this part](https://github.com/Parables/graphql-code-generator/blob/2ccebd6e678f0e72e2635b356c225ebdd03aa849/packages/plugins/dart/flutter-freezed/src/index.ts#L37) if that's the cause

**Comment by auaicn** [comment]
> @auaicn if I can ask for one more favour, please do take a look into the [/packages/plugins/dart/flutter-freezed/src/freezed-declaration-blocks/factory-block](https://github.com/Parables/graphql-code-generator/blob/6fbc54393b383e2ec7cd0a392cd9be6286697a95/packages/plugins/dart/flutter-freezed/src/freezed-declaration-blocks/factory-block.ts#L137) and figure out why there is a named constructor append to this factory block when using [mergedInputs](https://github.com/Parables/graphql-code-generator/blob/6fbc54393b383e2ec7cd0a392cd9be6286697a95/packages/plugins/dart/flutter-freezed/src/config.ts#L245) from the config.
> 
> Also, please update the tests for me. When I discovered these bugs, I had to make the test fail so that I could fix the bug and make them green again. Sadly enough, I haven't been able to get back to it ever since.
> 
> I need to fix that bug for the plugin to work as expected. I will submit a PR for a new version once this bug is fixed One more favour, please 🥺

I'll see what you asked after handling dart-language reserved words!

It seems merge target branch was not set properly but merged! It seems you treated that well, Thank you.

I'll do rest of the works with new branch from [fluter-freezed-v3.0.0](https://github.com/Parables/graphql-code-generator/tree/fluter-freezed-v3.0.0) branch

**Pull request merged**
